export const SET_PROJECT = 'SET_PROJECT';
export const SET_COLLABORATER = 'SET_COLLABORATER';
export const SET_TICKETS_PROGRESS = 'SET_TICKETS_PROGRESS';
export const SET_TICKETS_FINISH = 'SET_TICKETS_FINISH';

